
dependencies:
  - python=3.8
  - sqlite>=3.35                 # need 3.35 which has sqrt function
  - parallel
  - gnuplot
  - libcurl
  - compilers
  - automake
  - cmake
  - flex
  - bison
  - libmagic
  - pip
  - pip:
      - nvidia-pyindex
      - nvidia-tensorflow
      - keras==2.2.5
      - keras-rectified-adam==0.17.0
      - matplotlib
      - progressbar2
      - tqdm
      - ansicolors
      - imageio
      - scikit-image
      - sklearn
      - pandas
      - git+https://github.com/tomsilver/pddlgym@be55cbf458293edd419216ee71bead02d41c586d
      - -e .
