
name : latplan
dependencies:
  - python=3.8
  - pip
  - pip:
      - keras==2.2.5
      - h5py
      - matplotlib
      - progressbar2
      - keras-adabound
      - keras-rectified-adam
      - timeout_decorator
      - ansicolors
      - scipy==1.4.1
      - scikit-image
      - imageio
      - pillow
      - git+https://github.com/tomsilver/pddlgym
      - tqdm
      - nvidia-pyindex
      - nvidia-tensorflow
