#!/bin/bash

h=blind
n=$1

cat > $h-hanoi$n.sh <<EOF
#!/bin/bash
./plan.py $h 'run_hanoi("samples/hanoi${n}_fc2/","fc2",import_module("puzzles.hanoi"),$n)' |& tee \$(dirname \$0)/$h-hanoi$n.log
EOF
chmod +x $h-hanoi$n.sh

cat > $h-xhanoi$n.sh <<EOF
#!/bin/bash
./plan.py $h 'run_hanoi("samples/xhanoi${n}_fc2/","fc2",import_module("puzzles.hanoi"),$n)' |& tee \$(dirname \$0)/$h-xhanoi$n.log
EOF
chmod +x $h-xhanoi$n.sh


