#!/bin/bash

mode=$1
output_dir=$2

backup=$(dirname $(readlink -ef $0))/backup-$mode
scripts=$(dirname $(readlink -ef $0))/backup-scripts

usage (){
    echo "Usage: $0 mode output_dir"
    exit
}

if [ -z $mode ]
then
    echo "missing mode."
    usage
fi
if [ -z $output_dir ]
then
    echo "missing output directory."
    usage
fi
if [ ! -d $backup ]
then
    echo "mode argument ($mode) is illegal. should be one of: propositional, fol"
    usage
fi

mkdir -vp $output_dir

rsync -a -L $backup/ $output_dir/
for f in $scripts/*
do
    if ! (echo $f | grep -q "~")     # do not link backup files. watch out shell expansion for ~
    then
        ln -s $f $output_dir/$(basename $f)
    fi
done
